### ISSUE TITLE
Static file serve progress?

### ISSUE THREAD

**Issue by maximivanov** [jeehyukwon/nuxt-edge-serverless-template#2]
Hey there! This template helped me a lot. 
Is there any update on adding static file support? Like for `/favicon.ico` and `/browserconfig.xml` (both live in nuxt's `static` folder)

**Comment by tonyfromundefined** [comment]
Thank you very much for using my template.

As I proceeded with my personal project, there was a lot of progress on that template, and soon I will add it to this template. Static file serving feature will also be included in the upcoming update.

Thank you.

**Comment by emkman** [comment]
@jeehyukwon what is the purpose of the s3Sync plugin if not static file serving? Forgive me if I just don't understand that plugin's purpose.

**Comment by pschaub** [comment]
@jeehyukwon I am also interested into this, please let us know here once the update is ready.

**Comment by tonyfromundefined** [comment]
static file support is added in `0.0.4`.
But `0.0.3` to `0.0.4` has some deprecation.

- `@nuxtjs/axios`, `@nuxtjs/apollo` plugin is removed
- if you installed some library in your project, this should be contained in `dependencies` of `package.json` (The `externals` webpack option does not work in `build.extend()` from `nuxt.config.js` (It happened after updating Nuxt.js, but I'm not sure why)

so be careful for update your project.

**Comment by tonyfromundefined** [comment]
The current `externals` setting can be found on line `3542` of `/node_modules/nuxt/dist/nuxt.js`. There is currently an issue in which this setting can not be overridden in `nuxt.config.js`. Pull request to Nuxt.js is required.
